apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpgcb
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: bpgcb

  template:
    metadata:
      labels:
        app: bpgcb

    spec:
      restartPolicy: Always

      imagePullSecrets:
        - name: secret-automation

      containers:
        - name: bpgcb
          image: rhenancocev/bpgcb:2.0.0
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: bp-secrets

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "200m"

          volumeMounts:
            - name: data
              mountPath: /app/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bpgcb-pvc
