apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpgcb
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: bpgcb

  template:
    metadata:
      labels:
        app: bpgcb

    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      imagePullSecrets:
        - name: secret-automation

      containers:
        - name: bpgcb
          image: rhenancocev/bpgcb:2.2.5
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

          envFrom:
            - secretRef:
                name: bp-secrets

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "200m"

          volumeMounts:
            - name: data
              mountPath: /app/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bpgcb-pvc
